version: "3.9"
services:
  api:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # optional: live reload
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
