apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: aymendocker99/fastapi:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_HOSTNAME
            value: postgres
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: fastapi
          - name: DATABASE_USERNAME
            value: postgres
          - name: DATABASE_PASSWORD
            value: postgres
          - name: SECRET_KEY
            value: supersecretkey
          - name: ALGORITHM
            value: HS256
          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            value: "30"
        limits:


