apiVersion: kustomize.config.k8s.io/v1beta1
# Ensure the schema URL is accessible or use a local schema if needed
kind: Kustomization

resources:
- db-deploy.yaml
- deploy.yaml
- ingress.yaml
- namespace.yaml
- service.yaml

namespace: fastapi
images:
- name: aymendocker99/fastapi
  newTag: 79d413bc48a175444401b6a5b7c4450e135e6605
