apiVersion: kustomize.config.k8s.io/v1beta1
# Ensure the schema URL is accessible or use a local schema if needed
kind: Kustomization

resources:
- db-deploy.yaml
- deploy.yaml
- ingress.yaml
- namespace.yaml
- service.yaml

namespace: fastapi
images:
- name: aymendocker99/fastapi
  newTag: 944f94782c9e963e659c3b1d32672267fbbbbb62
