apiVersion: kustomize.config.k8s.io/v1beta1
# Ensure the schema URL is accessible or use a local schema if needed
kind: Kustomization

resources:
- deploy.yaml
- ingress.yaml
- namespace.yaml
- service.yaml

namespace: fastapi
images:
- name: aymendocker99/fastapi
  newTag: e1fab60133375550beaa2957e23cf6b68cf3ab88
