apiVersion: kustomize.config.k8s.io/v1
# Ensure the schema URL is accessible or use a local schema if needed
kind: Kustomization

resources:
- deploy.yaml
- ingress.yaml
- namespace.yaml
- service.yaml

namespace: fastapi
images:
- name: aymendocker99/fastapi
  newTag: b6bd5725
- name: aymendocker99/fastapi:latest
  newName: aymendocker99/fastapi
  newTag: ee11d422
