---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mistral-secrets
  namespace: fastapi
spec:
  encryptedData:
    MISTRAL_API_KEY: AgBG6/oDjei2cEpWHX/bZBEQ7r1gribs/HR5Tb1SX2LtLZXnFTh+Q3moqyEjfeWNoUjf5sN4aeYNDGYBA/w8ZStVHRhhuxFioyZ7h0kbbcWv9i3Se8deiW+zNC+34qGpBX94IkF0jK7XPTnKCXzZZJOK0VZ0fIxcmrio8b+2mV3wrcP1a8X1GbYwBsLvyrXsOZFgERaAvE/VowNVU49DCs3WYeJpC6b6MmBXeqCtmF/MvV4JgSb0xKiLPPgvH3vAOepoqoUZr8wJ3hNEFnwWV34AEjYtMys4+GGdDckeQ8vSULnda/rroYNAUkGQzbhqIelZM+IBNVa7qDwiaV4m30YLVH1dT80/Bm3cg4B0IIQLTYx1so1Qi1DCQgkiRdk6l9PGOujT3MYoUPVnVvfW0mOTAoS4u+xOc6yFEoiHJG0wEROj4tX+8Pzx4sxwMsGqxURQBN378lXtIxTv0OMsyvLY8ewy9P1iowl7SC6KWOnxcrkzM3fdMSL6p8nYUGntvTRcN5a1EytE4SQVqYpnMSrT3LayQ5xZVhX00Ke8wE23tHTv7DpFSMad5+YSbjdUtDV4lzEZ/pidyJKtvm5+kpKuoov1StmIvHoJfdj63slRM8krmBLTgUjOsevWCjweZ69sE5gg2JNq/X1i/9YrvGqK2liBhSnGkyRNrScwW+9/bKamZlC1tsdADeO8IOt6yjZzWSDkaBwaZDdqo5YAGdQeCIaFjeKH5ZLNuI7sxL2fWw==
  template:
    metadata:
      creationTimestamp: null
      name: mistral-secrets
      namespace: fastapi
